config/routes.rb
Rails.application.routes.draw do
  resources :summaries

  root 'home#index'

end

app/models/summarizer.rb
class Summarizer
  def self.call(raw_text)
    sentences = raw_text.gsub(/\s+/, ' ').strip.split(/\.|\?|!/)
    sentences_sorted = sentences.sort_by { |sentence| sentence.length }
    one_third = sentences_sorted.length / 3
    middle_third = sentences_sorted.slice(one_third, one_third + 1)
    ideal_sentences = sentences_sorted.select { |sentence| sentence =~ /is|are/ }
 
    ideal_sentences.join(".")
  end
end

app/models/summary.rb
class Summary < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  before_action :set_summary, only: [:show, :edit, :update, :destroy]

  # GET /summaries
  # GET /summaries.json
  def index
    @summaries = Summary.all
  end

  # GET /summaries/1
  # GET /summaries/1.json
  def show
  end

  # GET /summaries/new
  def new
    @summary = Summary.new
  end

  # GET /summaries/1/edit
  def edit
  end

  # POST /summaries
  # POST /summaries.json
  def create
    @summary = Summary.new(summary_params)
    @summary.summarized_text = Summarizer.call(@summary.raw_text)

    respond_to do |format|
      if @summary.save
        format.html { redirect_to @summary, notice: 'Summary was successfully created.' }
        format.json { render :show, status: :created, location: @summary }
      else
        format.html { render :new }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /summaries/1
  # PATCH/PUT /summaries/1.json
  def update
    respond_to do |format|
      if @summary.update(summary_params)
        format.html { redirect_to @summary, notice: 'Summary was successfully updated.' }
        format.json { render :show, status: :ok, location: @summary }
      else
        format.html { render :edit }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /summaries/1
  # DELETE /summaries/1.json
  def destroy
    @summary.destroy
    respond_to do |format|
      format.html { redirect_to summaries_url, notice: 'Summary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_summary
      @summary = Summary.find(params[:id])
    end

    def generate_summary(text)
      sentences = text.gsub(/\s+/, ' ').strip.split(/\.|\?|!/)
      sentences_sorted = sentences.sort_by { |sentence| sentence.length }
      one_third = sentences_sorted.length / 3
      one_third = sentences_sorted.slice(one_third, one_third + 1)
      ideal_sentences = sentences_sorted.select { |sentence| sentence =~ /is|are/ }
      ideal_sentences.join(".")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def summary_params
      params.require(:summary).permit(:raw_text, :summarized_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/views/home/index.html.erb
<h1>Party party party party!!!!!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RebootuRailsDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

<%= yield %>

</div>

</body>
</html>

app/views/summaries/_form.html.erb
<%= form_for(@summary) do |f| %>
  <% if @summary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@summary.errors.count, "error") %> prohibited this summary from being saved:</h2>

      <ul>
      <% @summary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :raw_text %><br>
    <%= f.text_area :raw_text, :cols => 100, :rows => 10 %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-danger" %>
  </div>
<% end %>

app/views/summaries/edit.html.erb
<h1>Editing Summary</h1>

<%= render 'form' %>

<%= link_to 'Show', @summary %> |
<%= link_to 'Back', summaries_path %>

app/views/summaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Summaries</h1>

<table>
  <thead>
    <tr>
      <th>Raw text</th>
      <th>Summarized text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @summaries.each do |summary| %>
      <tr>
        <td><%= summary.raw_text %></td>
        <td><%= summary.summarized_text %></td>
        <td><%= link_to 'Show', summary %></td>
        <td><%= link_to 'Edit', edit_summary_path(summary) %></td>
        <td><%= link_to 'Destroy', summary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Summary', new_summary_path, class: "btn btn-danger" %>

app/views/summaries/new.html.erb
<h1>New Summary</h1>

<%= render 'form' %>

<%= link_to 'Back', summaries_path %>

app/views/summaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Raw text:</strong>
  <%= @summary.raw_text %>
</p>

<p>
  <strong>Summarized text:</strong>
  <%= @summary.summarized_text %>
</p>

<%= link_to 'Edit', edit_summary_path(@summary) %> |
<%= link_to 'Back', summaries_path %>